# Generated by Django 3.2.7 on 2021-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_fileforanalysis_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Word')),
                ('count_of_documents', models.IntegerField(default=0, verbose_name='Count of documents with the word')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['-count_of_documents'],
            },
        ),
        migrations.AddField(
            model_name='fileforanalysis',
            name='file_format',
            field=models.CharField(default='docx', max_length=128, verbose_name='File format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileforanalysis',
            name='text_content',
            field=models.TextField(default=''),
        ),
    ]
