# Generated by Django 3.2.7 on 2021-09-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210907_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileforanalysis',
            name='file_format',
            field=models.CharField(default='docx', max_length=128, verbose_name='File format'),
        ),
    ]
