# Generated by Django 3.2.7 on 2021-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_fileforanalysis_file_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['name'], 'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AddField(
            model_name='fileforanalysis',
            name='words_added',
            field=models.BooleanField(default=False),
        ),
    ]
