# Generated by Django 3.2.7 on 2021-09-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210907_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileforanalysis',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='fileforanalysis',
            name='words_added',
        ),
    ]
