# Generated by Django 3.2.7 on 2021-09-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210907_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileforanalysis',
            name='file_format',
        ),
    ]
