# Generated by Django 3.2.7 on 2021-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_fileforanalysis_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileforanalysis',
            name='upload',
            field=models.FileField(upload_to='media/%Y/%m/%d', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='word',
            name='count_of_documents',
            field=models.IntegerField(default=1, verbose_name='Count of documents with the word'),
        ),
    ]
